### ISSUE TITLE
Not working in new kodi version

### ISSUE THREAD

**Issue by subash1089** [eintamil/repository.eintamil#30]
PythonToCppException

addons/plug-in.video.einthusan3 line 628

also line 395 and 484

**Comment by sagarcheruku** [comment]
The new version is not working for me as well (Einthusan Video Addon - Version 3.x” for Kodi 19.x (xbmc.python 3.x)). @eintamil Please have a look sir. thanks

**Comment by vjayapau** [comment]
It usually works fine, but occassionally saying 'EINTHUSAN ERROR' without loading any. Mainly happening in the evening times. Kodi verson 20.1
Can anyone shed some light on this issue?!

**Comment by eintamil** [comment]
Sorry for the delay in response. Can you add username and password in Add-on Settings Authentication. If it is still not working, please attach your Kodi.log file.

**Comment by vjayapau** [comment]
Hi,
Thanks for responding quickly. Much appreciated...

Please find the attached screen shots of account logon page and the 3 error
log pages attached.
The issue is still there even with the account information.
It is only occuring in the night time (Just wierd)

Hope the issue will get resolved...
Thanks in advance.

**Comment by vjayapau** [comment]
Hi,
Thanks for responding quickly. Much appreciated...

Please find the attached screen shots of account logon page and the 3 error
log pages attached.
The issue is still there even with the account information.
It is only occuring in the night time (Just wierd)

Hope the issue will get resolved...
Thanks in advance.

**Comment by vjayapau** [comment]
Hi,
Thanks for responding quickly. Much appreciated...

Please find the attached screen shots of account logon page and the error log attached.
![Account Screen](https://github.com/eintamil/repository.eintamil/assets/92879105/6ebc4855-33b1-4977-ad25-6afdc206d1ea)
![Einthusan Log report](https://github.com/eintamil/repository.eintamil/assets/92879105/de9e2d5b-b027-4e2d-982c-5da9eda6c18e)

The issue is still there even with the account information entered.
It is only occuring in the night time (Just wierd)

Hope the issue will get resolved...
Thanks in advance.

**Comment by alamirfan786** [comment]
I am also struggling in the evenings can someone please advise

**Comment by sameersyed** [comment]
I am also seeing the same error when I am trying to play anything.

**Comment by eintamil** [comment]
Unfortunately, it is a limitation introduced by the website for free accounts. 
Paid account premium users are not facing any error.

**Comment by eintamil** [comment]
Please try the below steps and comment if you are still facing the issue:
```
- Kindly uninstall the older version of the Einthusan addon
- Update to EinTamil Kodi Repository Version 1.1.0
- Install Einthusan addon Version 3.1.0
```

**Comment by alamirfan786** [comment]
Good afternoon, 
I have updated however same issue without my account works fine if I enable my membership account it won't play and gives an error. 
Kind regards, 


Yahoo Mail: Search, organise, conquer 
 
  On Sun, 1 Dec 2024 at 1:16, EinTamil Kodi ***@***.***> wrote:   


Closed #30 as completed.

**Comment by subash1089** [comment]
Same for me as well. Works fine without my account added.

**Comment by alamirfan786** [comment]
Any way to fix this as the account like everyone is a paid account

**Comment by eintamil** [comment]
Please share the logs to troubleshoot
